name: PR check

on:
  pull_request:

jobs:
#  code-quality:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build:ci
      env:
        CI: true
    - uses: vrutkovs/action-s2i@master
      with:
        path: "./package-contents"
        base: registry.access.redhat.com/ubi8/nodejs-10:latest
        image: todolist-tester:latest
    - name: Export Container Image
      run: |
        docker save --output todolist-tester.tar todolist-tester:latest
    - uses: actions/upload-artifact@v2
      with:
        name: todolist-tester-latest.tar
        path: todolist-tester.tar

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: |
        pwd
        ls -la
    - uses: actions/download-artifact@v2
      with:
        name: todolist-tester-latest.tar
    - run: |
        pwd
        ls -la
#    - run: |
#        docker load --input $(pwd)/todolist-tester.tar



#  security-scan:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: anchore/scan-action@master
#      with:
#        image-reference: "todolist-tester:latest"
#        fail-build: false
#        include-app-packages: true
#      id: vuln_scan
#    - run: |
#        echo ::set-output name=numVuln::$(jq --raw-output '.vulnerabilities | length' ${{steps.vuln_scan.outputs.vulnerabilities}})
#        echo ::set-output name=highVuln::$(jq 'reduce .vulnerabilities[] as $s(0; if $s.severity == "High" then .+1 else . end)' ${{steps.vuln_scan.outputs.vulnerabilities}})
#        echo ::set-output name=medVuln::$(jq 'reduce .vulnerabilities[] as $s(0; if $s.severity == "Medium" then .+1 else . end)' ${{steps.vuln_scan.outputs.vulnerabilities}})
#        echo ::set-output name=lowVuln::$(jq 'reduce .vulnerabilities[] as $s(0; if $s.severity == "Low" then .+1 else . end)' ${{steps.vuln_scan.outputs.vulnerabilities}})
#        echo ::set-output name=highPkg::$(jq --raw-output '.vulnerabilities[] | select(.severity == "High") | "|" + .package + "|" + .vuln + "|" + .url + "|\n"' ${{steps.vuln_scan.outputs.vulnerabilities}})
#      id: vuln_out
#    - uses: actions/github-script@0.9.0
#      with:
#        github-token: ${{secrets.GITHUB_TOKEN}}
#        script: |
#          github.issues.createComment({
#            issue_number: context.issue.number,
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            body: 'There are ${{steps.vuln_out.outputs.numVuln}} vulnerabilities present in this image\n\n🟡 There are ${{steps.vuln_out.outputs.lowVuln}} low vulnerabilities\n🟠 There are ${{steps.vuln_out.outputs.medVuln}} medium vulnerabilities\n🔴 There are ${{steps.vuln_out.outputs.highVuln}} high vulnerabilities'
#          })
#    - uses: Azure/container-scan@v0
#      id: azure_scan
#      with:
#        image-name: todolist-tester:latest
#        severity-threshold: 'UNKNOWN'
#    - run: |
#        cat ${{steps.azure_scan.outputs.scan-report-path}}
